# Generated by Django 5.2.5 on 2026-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramPage', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
