# Generated by Django 5.2.5 on 2026-02-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramPage', '0005_note_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
